name: Terraform Cleanup

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  cleanup:
    if: ${{ github.ref_name == 'main' }}
    name: Terraform cleanup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::858669496696:role/github-oidc-terraform-use-case
        aws-region: eu-west-2
    
    - name: Terraform Init
      id: init
      run: terraform init
    
    - name: Terraform Plan Destroy
      id: plan
      run: terraform plan -no-color