name: terraform-cicd

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-cicd:
    name: terraform-cicd
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::858669496696:role/github-oidc-terraform-use-case
        aws-region: eu-west-2

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color