name: Terraform CI/CD

on:
  push:
  pull_request:               # PRs into main (plan only)
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::858669496696:role/github-oidc-terraform-use-case
        aws-region: eu-west-2

    - name: Terraform fmt
      run: terraform fmt -check -recursive
      
    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color

  terraform-apply:
    name: Terraform apply
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::858669496696:role/github-oidc-terraform-use-case
        aws-region: eu-west-2

    - name: Terraform fmt
      run: terraform fmt -check -recursive
      
    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color
    
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
    